name: xr4all-env

channels:
- conda-forge

dependencies:
- python=3.7
- conda
- pip
- pythonocc-core=7.4.0
- pip:
  - flask-bcrypt
  - flask-restplus
  - Flask-Migrate
  - pyjwt
  - Flask-Script
  - flask_testing
  
